mode: rule
allow-lan: true
unified-delay: true
bind-address: '*'
log-level: silent
ipv6: true
geodata-mode: true
external-controller: 0.0.0.0:9090
external-ui: dashboard/dist
tcp-concurrent: true
interface-name: ""
enable-process: true
geodata-loader: memconservative
inbound-tfo: true
secret: ""
# geox-url: {mmdb: "https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb",geoip: "https://github.com/v2fly/geoip/releases/latest/download/geoip-only-cn-private.dat",geosite: "https://github.com/taamarin/v2ray-rules-dat/raw/release/GeoSite.dat"}
profile:
  store-selected: true
  store-fake-ip: false
experimental: {
    sniff-tls-sni: false,
    fingerprint: ""
}
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  force-domain:
    - '+'
  skip-domain: 
    - '+.google.com'
  port-whitelist:
    - 443
    - 80
hosts: {
  "cacerts.digicert.com": "104.21.21.147",
  "ota.googlezip.net": "127.0.0.1",
  "ota-cache1.googlezip.net": "127.0.0.1",
  "ota-cache2.googlezip.net": "127.0.0.1"
}
tun:
  enable: false
  device: Meta
  stack: system
  dns-hijack:
    - any:53
  auto-route: false
  auto-detect-interface: false
dns:
  enable: true
  ipv6: true
  prefer-h3: false
  default-nameserver:
    - 8.8.8.8
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter: [
    "*.local",
    "*.localhost",
  ]
  nameserver:
    - 1.1.1.1
  fallback: []
  fallback-filter:
    geoip: false
    geoip-code: "!ID"
    geosite: [GFW]
    ipcidr: []
    domain: ['+.google.com','+.facebook.com','+.youtube.com']
tproxy-port: 9898
mixed-port: 7890
proxies:
rule-providers:
  Direct:
    type: file
    behavior: classical
    path: "./direct.yaml"
  BlockAds:
    type: http
    behavior: classical
    path: "./BlockAds.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml
    interval: 86400
  Game:
    type: http
    behavior: classical
    path: "./Game.yaml"
    url: https://raw.githubusercontent.com/timothyratag/CFMA-FULL-RULE/main/Game.yaml
    interval: 86400
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: "./reject.yaml"
    interval: 86400
  Browsing_Dowload:
    type: http
    behavior: classical
    path: "./Browsing_Dowload.yaml"
    url: https://raw.githubusercontent.com/timothyratag/CFMA-FULL-RULE/main/Browsing_Dowload.yaml
    interval: 86400
  Streaming_Sosmed:
    type: file
    behavior: classical
    path: "./Streaming_Sosmed.yaml"
    url: https://raw.githubusercontent.com/timothyratag/CFMA-FULL-RULE/main/Streaming_Sosmed.yaml
    interval: 86400
proxy-providers:
  VPN:
    type: file
    path: "./VPN.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 10
proxy-groups:
- name: LOAD-BALANCE
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - VPN
  url: http://www.gstatic.com/generate_204
  interval: '60'
- name: PING-TEST
  type: url-test
  disable-udp: false
  use:
  - VPN
  url: http://www.gstatic.com/generate_204
  interval: '60'
  tolerance: '150'
- name: RELAY-TRAFFIC
  type: relay
  disable-udp: false
  use:
  - VPN
- name: FALLBACK
  type: fallback
  disable-udp: false
  use:
  - VPN
  url: http://www.gstatic.com/generate_204
  interval: '60'
- name: MANUAL-SELECT
  type: select
  disable-udp: false
  use:
  - VPN
- name: UMUM
  type: select
  disable-udp: false
  proxies:
  - LOAD-BALANCE
  - PING-TEST
  - RELAY-TRAFFIC
  - FALLBACK
  - MANUAL-SELECT
- name: OPSI•ADS
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - UMUM
- name: GAMING
  type: select
  disable-udp: false
  proxies:
  - LOAD-BALANCE
  - PING-TEST
  - RELAY-TRAFFIC
  - FALLBACK
  - MANUAL-SELECT
- name: OPSI•MLBB
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - GAMING
- name: SOSMED|TKTOK|YT|IG|FB
  type: select
  disable-udp: false
  proxies:
  - LOAD-BALANCE
  - PING-TEST
  - RELAY-TRAFFIC
  - FALLBACK
  - MANUAL-SELECT
rules:
- AND, ((DST-PORT, 1024-19299), (NETWORK, UDP)), DIRECT
- AND, ((DST-PORT, 19311-65535), (NETWORK, UDP)), DIRECT
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- RULE-SET,Game,OPSI•MLBB
- RULE-SET,BlockAds,OPSI•ADS
- RULE-SET,Direct,DIRECT
- RULE-SET,Browsing_Dowload,UMUM
- RULE-SET,Streaming_Sosmed,SOSMED|TKTOK|YT|IG|FB
- MATCH,GLOBAL